from pydantic import BaseModel

class NIRF_C7(BaseModel):
    year: int
    branch_name: str
    branch_level: str
    approved_intake: int
    actual_intake: int
    in_state_first_year: int
    out_of_state_first_year: int
    international_first_year: int
    in_state_lateral_entry: int
    out_of_state_lateral_entry: int
    international_lateral_entry: int
    total_male_students: int
    total_female_students: int
    total_students: int
    economically_backward_students: int
    sc_students: int
    st_students: int
    obc_students: int
    physically_challenged_students: int
    students_graduating_in_min_time: int
    upsc_students: int
    state_gov_students: int
    gate_students: int
    cat_students: int
    other_exam_students: int
    placed_students: int
    min_salary: float
    max_salary: float
    avg_salary: float
    higher_studies_with_exam: int
    higher_studies_without_exam: int
    entrepreneurship_students: int

    def todict(self):
        return {
            "year": int(self.year),
            "program_name": str(self.program_name),
            "program_level": str(self.program_level),
            "approved_intake": int(self.approved_intake),
            "actual_intake": int(self.actual_intake),
            "in_state_first_year": int(self.in_state_first_year),
            "out_of_state_first_year": int(self.out_of_state_first_year),
            "international_first_year": int(self.international_first_year),
            "in_state_lateral_entry": int(self.in_state_lateral_entry),
            "out_of_state_lateral_entry": int(self.out_of_state_lateral_entry),
            "international_lateral_entry": int(self.international_lateral_entry),
            "total_male_students": int(self.total_male_students),
            "total_female_students": int(self.total_female_students),
            "total_students": int(self.total_students),
            "economically_backward_students": int(self.economically_backward_students),
            "sc_students": int(self.sc_students),
            "st_students": int(self.st_students),
            "obc_students": int(self.obc_students),
            "physically_challenged_students": int(self.physically_challenged_students),
            "students_graduating_in_min_time": int(self.students_graduating_in_min_time),
            "upsc_students": int(self.upsc_students),
            "state_gov_students": int(self.state_gov_students),
            "gate_students": int(self.gate_students),
            "cat_students": int(self.cat_students),
            "other_exam_students": int(self.other_exam_students),
            "placed_students": int(self.placed_students),
            "min_salary": float(self.min_salary),
            "max_salary": float(self.max_salary),
            "avg_salary": float(self.avg_salary),
            "higher_studies_with_exam": int(self.higher_studies_with_exam),
            "higher_studies_without_exam": int(self.higher_sties_without_exam),
            "entrepreneurship_students": int(self.entrepreneurship_students)
        }